[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp_sqlite_memory_bank"
version = "0.1.0"
description = "A dynamic, agent/LLM-friendly SQLite memory bank for MCP servers."
authors = [
    { name="Robert Meisner", email="your-email@example.com" }
]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "fastapi>=0.100.0",
    "uvicorn>=0.22.0",
    "pydantic>=1.10.0"
]
  
[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["*__pycache__*", "*.pyc", "*.pyo"]
